/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Doctor;

import Model.EcoSystem.EcoSystem;
import Model.EcoSystem.Network;
import Model.Enterprise.Enterprise;
import Model.Organization.Organization;
import Model.Orphan.Orphan;
import Model.UserAccount.UserAccount;
import Model.WorkQueue.MedCareRequest;
import Model.WorkQueue.PharmacistWorkRequest;
import Model.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alilovepeach
 */
public class RequestPharmacistJFrame extends javax.swing.JFrame {

    EcoSystem ecosys;
    Network network;
    Enterprise enterprise;
    Organization org;
    UserAccount useraccount;
    Orphan orphan;
    MedCareRequest request;
    /**
     * Creates new form RequestPharmacistJFrame
     */
    public RequestPharmacistJFrame() {
        initComponents();
    }

    public RequestPharmacistJFrame(EcoSystem ecosys, Network network, Enterprise enterprise, Organization org, UserAccount useraccount, Orphan orphan, MedCareRequest request) {
        initComponents();
        this.setVisible(true);
        this.ecosys=ecosys;
        this.network=network;
        this.enterprise=enterprise;
        this.org=org;
        this.useraccount=useraccount;
        this.orphan=orphan;
        this.request=request;
        
        
        for (Network net : ecosys.getNetworkList()) {
            
            for (Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()) {
                
                if (ent.equals(enterprise)) {
                    
                    network = net;
                }
            }
        }

        
        populatePtTable();
    }
    
    public void populatePtTable() {

        DefaultTableModel model = (DefaultTableModel) tblWorkRequests.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest phrequest : orphan.getWorkQueue().getWorkRequestList()) {
            
            if (phrequest instanceof PharmacistWorkRequest) {

                Object[] row = new Object[model.getColumnCount()];
                
                row[0] = phrequest;
                row[1] = phrequest.getOrphan().getId();
                row[2] = phrequest.getReceiver();
                row[3] = phrequest.getStatus();
                
                
                
                if (phrequest instanceof MedCareRequest) {
                    String result = ((MedCareRequest) phrequest).getDoctorResult();
                    row[4] = result == null ? "Waiting" : result;

                } else if (phrequest instanceof PharmacistWorkRequest) {
                    String result = ((PharmacistWorkRequest) phrequest).getResult();
                    row[4] = result == null ? "Waiting" : result;
                }
                
                model.addRow(row);

            }
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequests = new javax.swing.JTable();
        requestlBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        messFID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel2.setkEndColor(new java.awt.Color(240, 80, 83));
        kGradientPanel2.setkStartColor(new java.awt.Color(225, 238, 195));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(800, 520));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblWorkRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Child ID", "Recipient", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkRequests);

        kGradientPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 730, 280));

        requestlBtn.setBackground(new java.awt.Color(195, 55, 100));
        requestlBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        requestlBtn.setForeground(new java.awt.Color(255, 255, 255));
        requestlBtn.setText("Request");
        requestlBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        requestlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestlBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(requestlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 194, 40));

        backBtn.setBackground(new java.awt.Color(195, 55, 100));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Close");
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Message");
        kGradientPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 160, -1));

        messFID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        messFID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(225, 238, 195)));
        kGradientPanel2.add(messFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 460, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Request Pharmaceutical Therapy");
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void requestlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestlBtnActionPerformed
        // TODO add your handling code here:
        
        String message = messFID.getText();
        
        //if message is emty
        
        if (message.equals("") || message.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in message.", 
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //send the request
        
        PharmacistWorkRequest request = new PharmacistWorkRequest();
        
        request.setSender(useraccount);
        request.setOrphan(orphan);
        request.setStatus("Pending");
        request.setMessage(message);
       

        orphan.getWorkQueue().getWorkRequestList().add(request);
        
        enterprise.getWorkQueue().getWorkRequestList().add(request);

        JOptionPane.showMessageDialog(this, "Pharmaceutical Therapy Request has been sent, you may now close this window", 
                "Information", JOptionPane.INFORMATION_MESSAGE);
        
        populatePtTable();
        
        //clear
        messFID.setText("");
    }//GEN-LAST:event_requestlBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestPharmacistJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestPharmacistJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestPharmacistJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestPharmacistJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestPharmacistJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField messFID;
    private javax.swing.JButton requestlBtn;
    private javax.swing.JTable tblWorkRequests;
    // End of variables declaration//GEN-END:variables
}
