/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.OrphanRegister;

import Model.EcoSystem.EcoSystem;
import Model.EcoSystem.Network;
import Model.Enterprise.Enterprise;
import Model.Enterprise.OrphanShelterEnterprise;
import Model.Organization.Organization;
import Model.Organization.OrphanManagementOrganization;
import Model.Orphan.Orphan;
import Model.UserAccount.UserAccount;
import Model.WorkQueue.OrphanManagerRequest;
import java.awt.Image;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author alilovepeach
 */
public class OrphanRegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrpanRegisterJPanel
     */
    private EcoSystem ecosys;
    private Network network;
    private Organization org;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private ImageIcon orphanImage;
    private File imageFile;
    private OrphanShelterEnterprise orpEnterprise;
    private Boolean validate = false;

    public OrphanRegisterJPanel() {
        initComponents();
    }
    
    public OrphanRegisterJPanel(EcoSystem ecosys, Network network, Enterprise enterprise, 
            Organization org, UserAccount useraccount) {
        initComponents();
        this.ecosys=ecosys;
        this.network=network;
        this.enterprise=enterprise;
        this.org=org;
        this.userAccount=useraccount;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSpinner1 = new javax.swing.JSpinner();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        btnRegisterOrphan = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        fieldOrphanName = new javax.swing.JTextField();
        lblMessage5 = new javax.swing.JLabel();
        lblMessage6 = new javax.swing.JLabel();
        lblMessage7 = new javax.swing.JLabel();
        lblMessage8 = new javax.swing.JLabel();
        lblMessage12 = new javax.swing.JLabel();
        btnUploadPhoto = new javax.swing.JButton();
        fieldPhoto = new javax.swing.JTextField();
        maleRadioBtn = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        jLabelImage = new javax.swing.JLabel();
        raceComboBox = new javax.swing.JComboBox<>();
        ageComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 204, 255));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(101, 78, 163));
        kGradientPanel1.setkStartColor(new java.awt.Color(234, 175, 200));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegisterOrphan.setText("Register");
        btnRegisterOrphan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterOrphanActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnRegisterOrphan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 100, 30));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitle.setText("Register Orphan");
        kGradientPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));
        kGradientPanel1.add(fieldOrphanName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 217, -1));

        lblMessage5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMessage5.setText("Name:");
        kGradientPanel1.add(lblMessage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        lblMessage6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMessage6.setText("Age:");
        kGradientPanel1.add(lblMessage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        lblMessage7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMessage7.setText("Sex:");
        kGradientPanel1.add(lblMessage7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        lblMessage8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMessage8.setText("Race:");
        kGradientPanel1.add(lblMessage8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 40, -1));

        lblMessage12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMessage12.setText("Photo:");
        kGradientPanel1.add(lblMessage12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        btnUploadPhoto.setText("Upload");
        btnUploadPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPhotoActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnUploadPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 100, -1));
        kGradientPanel1.add(fieldPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 217, -1));

        buttonGroup1.add(maleRadioBtn);
        maleRadioBtn.setSelected(true);
        maleRadioBtn.setText("Male");
        maleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioBtnActionPerformed(evt);
            }
        });
        kGradientPanel1.add(maleRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        buttonGroup1.add(rbtnFemale);
        rbtnFemale.setText("Female");
        rbtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemaleActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rbtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));
        kGradientPanel1.add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 200, 200));

        raceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unknown", "American Indian or Alaska Native", "Black or African American", "Native Hawaiian or Other Pacific Islander", "Asian", "White" }));
        kGradientPanel1.add(raceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 220, -1));

        ageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));
        kGradientPanel1.add(ageComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 220, -1));

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterOrphanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterOrphanActionPerformed

        String name = fieldOrphanName.getText();

        String age = ageComboBox.getSelectedItem().toString();

        String race = raceComboBox.getSelectedItem().toString();
        String photo = fieldPhoto.getText();

        Pattern special = Pattern.compile("[^a-z0-9]", Pattern.CASE_INSENSITIVE);
//        Pattern phone = Pattern.compile("[^a-z]", Pattern.CASE_INSENSITIVE);
        Pattern number = Pattern.compile("[0-9]", Pattern.CASE_INSENSITIVE);
//        Pattern emailVailidation = Pattern.compile("^[A-Za-z0-9+_.-][@][A-Za-z0-9.-]+$");

        Matcher matcherName = special.matcher(name);
        Matcher matcherNameNumber = number.matcher(name);

        boolean nameContainsSymbols = matcherName.find();
        boolean nameContainsNumber = matcherNameNumber.find();

        if (name.isEmpty() || age.isEmpty() || photo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "please fill all field");
            this.validate = true;
        } else if (nameContainsSymbols) {
            JOptionPane.showMessageDialog(null, "Name Contains invalid Symbols");
            this.validate = true;
        } else if (nameContainsNumber) {
            JOptionPane.showMessageDialog(null, "Name Contains invalid Number");
            this.validate = true;
        } else {
            this.validate = false;
            Orphan orphan = ((OrphanShelterEnterprise) enterprise).getOrphanDirectory().createOrphan(name);
            orphan.setAge(Integer.valueOf(age));
            if (maleRadioBtn.isSelected()) {
                orphan.setSex("male");
            } else {
                orphan.setSex("female");
            }
            orphan.setRace(race);
            orphan.setPhoto(photo);
            
            
            // create work request
            OrphanManagerRequest request = new OrphanManagerRequest();
            request.setMessage("New Orphan");
            request.setSender(userAccount);
            request.setStatus("Waiting for Manager");
            request.setOrphan(orphan);
            
            //add work request into workqueue
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            enterprise.getWorkQueue().getWorkRequestList().add(request);
            
            JOptionPane.showMessageDialog(null, "Successfully registered!");
        }
    }//GEN-LAST:event_btnRegisterOrphanActionPerformed

    private void btnUploadPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPhotoActionPerformed

        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);

        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();

            fieldPhoto.setText(selectedImagePath);
            ImageIcon ii = new ImageIcon(selectedImagePath);
            Image image = ii.getImage().getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH);

            jLabelImage.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_btnUploadPhotoActionPerformed

    private void maleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioBtnActionPerformed

    private void rbtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFemaleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ageComboBox;
    private javax.swing.JButton btnRegisterOrphan;
    private javax.swing.JButton btnUploadPhoto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fieldOrphanName;
    private javax.swing.JTextField fieldPhoto;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JSpinner jSpinner1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblMessage12;
    private javax.swing.JLabel lblMessage5;
    private javax.swing.JLabel lblMessage6;
    private javax.swing.JLabel lblMessage7;
    private javax.swing.JLabel lblMessage8;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JComboBox<String> raceComboBox;
    private javax.swing.JRadioButton rbtnFemale;
    // End of variables declaration//GEN-END:variables
}
