/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AdministrativeRole;

import Model.EcoSystem.EcoSystem;
import Model.EcoSystem.Network;
import Model.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    EcoSystem ecosys;
    UserAccount useraccount;

    /**
     * Creates new form ManageNetworkJPanel
     */
    public ManageNetworkJPanel() {
        initComponents();
    }

    public ManageNetworkJPanel(EcoSystem ecosys, UserAccount useraccount) {
        initComponents();
        this.ecosys = ecosys;
        this.useraccount = useraccount;
        refreshNetworkList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel3 = new keeptoo.KGradientPanel();
        lblTitle = new javax.swing.JLabel();
        lblNetworkList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNetwork = new javax.swing.JTable();
        lblEmployeeName = new javax.swing.JLabel();
        txtNetworkName = new javax.swing.JTextField();
        btnCreateNetwork = new javax.swing.JButton();
        btnDeleteNetwork = new javax.swing.JButton();
        btnUpdateNetwork = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        kGradientPanel3.setkEndColor(new java.awt.Color(255, 221, 225));
        kGradientPanel3.setkStartColor(new java.awt.Color(238, 156, 167));
        kGradientPanel3.setPreferredSize(new java.awt.Dimension(800, 520));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Manage Network");

        lblNetworkList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNetworkList.setForeground(new java.awt.Color(255, 255, 255));
        lblNetworkList.setText("Network List:");

        tbNetwork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbNetwork);
        if (tbNetwork.getColumnModel().getColumnCount() > 0) {
            tbNetwork.getColumnModel().getColumn(0).setResizable(false);
        }

        lblEmployeeName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmployeeName.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeName.setText(" Name:");

        txtNetworkName.setBackground(new java.awt.Color(245, 245, 255));

        btnCreateNetwork.setBackground(new java.awt.Color(238, 156, 167));
        btnCreateNetwork.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateNetwork.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateNetwork.setText("Create Network");
        btnCreateNetwork.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNetworkActionPerformed(evt);
            }
        });

        btnDeleteNetwork.setBackground(new java.awt.Color(238, 156, 167));
        btnDeleteNetwork.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteNetwork.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteNetwork.setText("Delete Network");
        btnDeleteNetwork.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeleteNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNetworkActionPerformed(evt);
            }
        });

        btnUpdateNetwork.setBackground(new java.awt.Color(238, 156, 167));
        btnUpdateNetwork.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateNetwork.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateNetwork.setText("Update Network");
        btnUpdateNetwork.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdateNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNetworkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(lblTitle))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblNetworkList))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txtNetworkName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCreateNetwork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateNetwork, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btnDeleteNetwork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblTitle)
                .addGap(61, 61, 61)
                .addComponent(lblNetworkList)
                .addGap(19, 19, 19)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblEmployeeName)
                        .addGap(23, 23, 23)
                        .addComponent(txtNetworkName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnCreateNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnDeleteNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        add(kGradientPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNetworkActionPerformed

        String name = txtNetworkName.getText();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Network name cannot be empty", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //check if ecosystem can get network list
        if (this.ecosys.getNetworkList().isEmpty() || this.ecosys.nameIsUnique(name)) {
            Network newNetwork = this.ecosys.createNetwork(name);
            txtNetworkName.setText("");
            //update network list
            refreshNetworkList();
            JOptionPane.showMessageDialog(this, "New network added", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Network existed", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateNetworkActionPerformed

    private void btnDeleteNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNetworkActionPerformed
        try {
            int selectedRow = tbNetwork.getSelectedRow();

            Network nw = (Network) tbNetwork.getValueAt(selectedRow, 0);

            if (selectedRow >= 0) {
                this.ecosys.deleteNetwork(nw);
                txtNetworkName.setText("");
                refreshNetworkList();
                JOptionPane.showMessageDialog(this, "Network deleted", "Information", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Please choose a network");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please choose a network");
        }

    }//GEN-LAST:event_btnDeleteNetworkActionPerformed

    private void btnUpdateNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNetworkActionPerformed
        try {
            String keyword = txtNetworkName.getText();
            int selectedRow = tbNetwork.getSelectedRow();

            Network nw = (Network) tbNetwork.getValueAt(selectedRow, 0);

            if (selectedRow >= 0) {
                if (!txtNetworkName.getText().isEmpty()) {
                    if (this.ecosys.nameIsUnique(keyword)) {
                        nw.setName(keyword);
                        txtNetworkName.setText("");
                        refreshNetworkList();
                        JOptionPane.showMessageDialog(this, "Newetwork updated", "Information", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Network existed");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Please fill the textfield");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Please choose a network");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please choose a network");
        }

    }//GEN-LAST:event_btnUpdateNetworkActionPerformed

    private void refreshNetworkList() {

        DefaultTableModel model = (DefaultTableModel) tbNetwork.getModel();
        model.setRowCount(0);

        for (Network n : this.ecosys.getNetworkList()) {

            Object objects[] = new Object[1];
            objects[0] = n;
            //add new row
            model.addRow(objects);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateNetwork;
    private javax.swing.JButton btnDeleteNetwork;
    private javax.swing.JButton btnUpdateNetwork;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblNetworkList;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tbNetwork;
    private javax.swing.JTextField txtNetworkName;
    // End of variables declaration//GEN-END:variables
}
