/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AdministrativeRole;

import Model.EcoSystem.EcoSystem;
import Model.EcoSystem.Network;
import Model.Enterprise.Enterprise;
import Model.Role.EnterpriseAdminRole;
import Model.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    EcoSystem ecosys;
    UserAccount useraccount;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseJPanel() {
        initComponents();
    }

    public ManageEnterpriseJPanel(EcoSystem ecosys, UserAccount useraccount) {
        initComponents();
        this.ecosys = ecosys;
        this.useraccount = useraccount;
        populateNetworkCombo();
        populateEnterpriseCombo();
        refreshEnterpriseList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnterpriseName2 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        lblTitle = new javax.swing.JLabel();
        lblEnterpriseList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprises = new javax.swing.JTable();
        lblSelectEnterpriseType = new javax.swing.JLabel();
        lblEnterpriseName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnCreateEnterprise = new javax.swing.JButton();
        lblSelectNetwork = new javax.swing.JLabel();
        cmbNetworkList = new javax.swing.JComboBox();
        btnUpdateEnter = new javax.swing.JButton();
        btnDeleteEnter = new javax.swing.JButton();
        EnterpriseCombo = new javax.swing.JComboBox();
        lblEnterpriseName1 = new javax.swing.JLabel();
        txtAdminName = new javax.swing.JTextField();
        lblEnterpriseName3 = new javax.swing.JLabel();
        txtAdminPass = new javax.swing.JTextField();

        lblEnterpriseName2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEnterpriseName2.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterpriseName2.setText("Enterprise Name:");

        txtName1.setBackground(new java.awt.Color(245, 245, 255));

        setLayout(new java.awt.BorderLayout());

        kGradientPanel3.setkEndColor(new java.awt.Color(255, 221, 225));
        kGradientPanel3.setkStartColor(new java.awt.Color(238, 156, 167));
        kGradientPanel3.setPreferredSize(new java.awt.Dimension(800, 520));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Manage Enterprise");
        kGradientPanel3.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        lblEnterpriseList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEnterpriseList.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterpriseList.setText("Enterprise List:");
        kGradientPanel3.add(lblEnterpriseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        tblEnterprises.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "Network", "Admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnterprises);

        kGradientPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 450, 360));

        lblSelectEnterpriseType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSelectEnterpriseType.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectEnterpriseType.setText("Select Enterprise Type:");
        kGradientPanel3.add(lblSelectEnterpriseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        lblEnterpriseName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEnterpriseName.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterpriseName.setText("Enterprise Name:");
        kGradientPanel3.add(lblEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        txtName.setBackground(new java.awt.Color(245, 245, 255));
        kGradientPanel3.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 200, 32));

        btnCreateEnterprise.setBackground(new java.awt.Color(238, 156, 167));
        btnCreateEnterprise.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateEnterprise.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateEnterprise.setText("Create Enterprise");
        btnCreateEnterprise.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEnterpriseActionPerformed(evt);
            }
        });
        kGradientPanel3.add(btnCreateEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 130, 33));

        lblSelectNetwork.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSelectNetwork.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectNetwork.setText("Select Network:");
        kGradientPanel3.add(lblSelectNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, 28));

        cmbNetworkList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNetworkListItemStateChanged(evt);
            }
        });
        cmbNetworkList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNetworkListActionPerformed(evt);
            }
        });
        kGradientPanel3.add(cmbNetworkList, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 200, 29));

        btnUpdateEnter.setBackground(new java.awt.Color(238, 156, 167));
        btnUpdateEnter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateEnter.setText("Update Enterprise");
        btnUpdateEnter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdateEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEnterActionPerformed(evt);
            }
        });
        kGradientPanel3.add(btnUpdateEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 130, 35));

        btnDeleteEnter.setBackground(new java.awt.Color(238, 156, 167));
        btnDeleteEnter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteEnter.setText("Delete Enterprise");
        btnDeleteEnter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeleteEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEnterActionPerformed(evt);
            }
        });
        kGradientPanel3.add(btnDeleteEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 130, 35));

        EnterpriseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterpriseComboActionPerformed(evt);
            }
        });
        kGradientPanel3.add(EnterpriseCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 200, 30));

        lblEnterpriseName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEnterpriseName1.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterpriseName1.setText("Enterprise Admin Name:");
        kGradientPanel3.add(lblEnterpriseName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        txtAdminName.setBackground(new java.awt.Color(245, 245, 255));
        kGradientPanel3.add(txtAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 200, 32));

        lblEnterpriseName3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEnterpriseName3.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterpriseName3.setText("Enterprise Admin Password:");
        kGradientPanel3.add(lblEnterpriseName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        txtAdminPass.setBackground(new java.awt.Color(245, 245, 255));
        kGradientPanel3.add(txtAdminPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 200, 32));

        add(kGradientPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNetworkListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNetworkListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNetworkListActionPerformed

    private void btnUpdateEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEnterActionPerformed
        try {
            String keyword = txtName.getText();
            int selectedRow = tblEnterprises.getSelectedRow();
            Network nw = (Network) cmbNetworkList.getSelectedItem();
            String adminname = txtAdminName.getText();
            String pw = txtAdminPass.getText();

            Enterprise ent = (Enterprise) tblEnterprises.getValueAt(selectedRow, 0);

            if (selectedRow >= 0) {
                if ((!txtName.getText().isEmpty()) && (!adminname.isEmpty()) && (!pw.isEmpty())) {
                    if (nw.getEnterpriseDirectory().nameIsUnique(keyword)) {
                        if (this.ecosys.getUserAccountDirectory().userNameIsUnique(adminname)) {
                            ent.setName(keyword);
                            ent.getEnterpriseAdmin().setUsername(adminname);
                            ent.getEnterpriseAdmin().setPassword(pw);

                            txtName.setText("");
                            txtAdminName.setText("");
                            txtAdminPass.setText("");

                            refreshEnterpriseList();

                            JOptionPane.showMessageDialog(this, "Enterprise updated", "Information", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "The enterprise admin already existed", "Warning", JOptionPane.WARNING_MESSAGE);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Enterprise name existed");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Please fill the textfield");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Please choose an Enterprise");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please choose an enterprise");
        }

    }//GEN-LAST:event_btnUpdateEnterActionPerformed

    private void btnDeleteEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEnterActionPerformed
        try {
            int selectedRow = tblEnterprises.getSelectedRow();
            Network nw = (Network) cmbNetworkList.getSelectedItem();

            Enterprise ent = (Enterprise) tblEnterprises.getValueAt(selectedRow, 0);

            if (selectedRow >= 0) {
                UserAccount admin = ent.getEnterpriseAdmin();
                this.ecosys.getUserAccountDirectory().deleteUserAccount(admin);
                nw.getEnterpriseDirectory().deleteEnterprise(ent);

                txtName.setText("");
                txtAdminName.setText("");
                txtAdminPass.setText("");
                
                refreshEnterpriseList();
                JOptionPane.showMessageDialog(this, "Enterprise deleted", "Information", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Please choose an Enterprise");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please choose an Enterprise");
        }

    }//GEN-LAST:event_btnDeleteEnterActionPerformed

    private void btnCreateEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEnterpriseActionPerformed
        String name = txtName.getText();
        Network nw = (Network) cmbNetworkList.getSelectedItem();
        String adminname = txtAdminName.getText();
        String pw = txtAdminPass.getText();

        if (nw != null) {
            if ((!name.isEmpty()) && (!adminname.isEmpty()) && (!pw.isEmpty())) {
                if (nw.getEnterpriseDirectory().nameIsUnique(name)) {
                    if (this.ecosys.getUserAccountDirectory().userNameIsUnique(adminname)) {
                        Enterprise.Type type = (Enterprise.Type) EnterpriseCombo.getSelectedItem();
                        Enterprise newEnter = nw.getEnterpriseDirectory().createAndAddEnterprise(name, type);

                        UserAccount enterpriseAdmin = new UserAccount();
                        enterpriseAdmin.setUsername(adminname);
                        enterpriseAdmin.setPassword(pw);
                        enterpriseAdmin.setRole(new EnterpriseAdminRole());
                        enterpriseAdmin.setNetwork(nw);
                        newEnter.setEnterpriseAdmin(enterpriseAdmin);

                        JOptionPane.showMessageDialog(this, "new Enterprise added", "Information", JOptionPane.INFORMATION_MESSAGE);

                        txtName.setText("");
                        txtAdminName.setText("");
                        txtAdminPass.setText("");

                        refreshEnterpriseList();

                    } else {
                        JOptionPane.showMessageDialog(this, "The enterprise admin already existed", "Warning", JOptionPane.WARNING_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Enterprise already existed", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "All fields cannot be empty", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please choose a network", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnCreateEnterpriseActionPerformed

    private void EnterpriseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterpriseComboActionPerformed

    }//GEN-LAST:event_EnterpriseComboActionPerformed

    private void cmbNetworkListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNetworkListItemStateChanged
        refreshEnterpriseList();
    }//GEN-LAST:event_cmbNetworkListItemStateChanged
    public void populateNetworkCombo() {
        cmbNetworkList.removeAllItems();

        for (Network nw : this.ecosys.getNetworkList()) {
            cmbNetworkList.addItem(nw);
        }

    }

    private void refreshEnterpriseList() {

        DefaultTableModel model = (DefaultTableModel) tblEnterprises.getModel();
        model.setRowCount(0);
        Network selectedNetwork = (Network) cmbNetworkList.getSelectedItem();

        if (selectedNetwork != null) {

            for (Enterprise e : selectedNetwork.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[4];
                row[0] = e;
                row[1] = e.getType();
                row[2] = selectedNetwork.getName();
                row[3] = e.getEnterpriseAdmin();

                model.addRow(row);
            }
        }

    }

    private void populateEnterpriseCombo() {
        EnterpriseCombo.removeAllItems();

        for (Enterprise.Type type : Enterprise.Type.values()) {
            EnterpriseCombo.addItem(type);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox EnterpriseCombo;
    private javax.swing.JButton btnCreateEnterprise;
    private javax.swing.JButton btnDeleteEnter;
    private javax.swing.JButton btnUpdateEnter;
    private javax.swing.JComboBox cmbNetworkList;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel lblEnterpriseList;
    private javax.swing.JLabel lblEnterpriseName;
    private javax.swing.JLabel lblEnterpriseName1;
    private javax.swing.JLabel lblEnterpriseName2;
    private javax.swing.JLabel lblEnterpriseName3;
    private javax.swing.JLabel lblSelectEnterpriseType;
    private javax.swing.JLabel lblSelectNetwork;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblEnterprises;
    private javax.swing.JTextField txtAdminName;
    private javax.swing.JTextField txtAdminPass;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    // End of variables declaration//GEN-END:variables
}
