/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Adopter;

import Model.EcoSystem.EcoSystem;
import Model.EcoSystem.Network;
import Model.Enterprise.AdoptionEnterprise;
import Model.Organization.AdopterOrganization;
import Model.Orphan.Orphan;
import Model.UserAccount.UserAccount;
import java.awt.Image;
import java.nio.file.Paths;
import javax.swing.ImageIcon;

/**
 *
 * @author Ma2017
 */
public class ViewOrphanDetailJFrame extends javax.swing.JFrame {

    EcoSystem ecosys;
    Network network;
    AdoptionEnterprise enterprise;
    AdopterOrganization org;
    UserAccount useraccount;
    Orphan o;

    /**
     * Creates new form ViewOrphanDetailJFrame
     */
    public ViewOrphanDetailJFrame() {
        initComponents();
    }

    public ViewOrphanDetailJFrame(EcoSystem ecosys, Network network, AdoptionEnterprise enterprise, AdopterOrganization org, UserAccount useraccount, Orphan orphan) {
        initComponents();
        this.setVisible(true);
        this.ecosys = ecosys;
        this.network = network;
        this.enterprise = enterprise;
        this.org = org;
        this.useraccount = useraccount;
        this.o = orphan;
        SexField.setEnabled(false);
        populateAllDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel3 = new keeptoo.KGradientPanel();
        lblTitle = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblMessage5 = new javax.swing.JLabel();
        txtOrphanfName = new javax.swing.JTextField();
        lblMessage7 = new javax.swing.JLabel();
        txtOrphanAge = new javax.swing.JTextField();
        lblMessage8 = new javax.swing.JLabel();
        lblMessage9 = new javax.swing.JLabel();
        txtOrphanRace = new javax.swing.JTextField();
        lblMessage12 = new javax.swing.JLabel();
        txtOrphanMessageFromDr = new javax.swing.JTextField();
        lblMessage11 = new javax.swing.JLabel();
        parFeedbackField = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        SexField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel3.setkEndColor(new java.awt.Color(247, 183, 51));
        kGradientPanel3.setkStartColor(new java.awt.Color(252, 74, 26));
        kGradientPanel3.setPreferredSize(new java.awt.Dimension(800, 520));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText(" Orphan Detail");

        lblPhoto.setText("Photo");

        lblMessage5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMessage5.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMessage5.setText("Name:");

        txtOrphanfName.setEnabled(false);

        lblMessage7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMessage7.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMessage7.setText("Age:");

        txtOrphanAge.setEnabled(false);

        lblMessage8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMessage8.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMessage8.setText("Sex:");

        lblMessage9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMessage9.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMessage9.setText("Race:");

        txtOrphanRace.setEnabled(false);

        lblMessage12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMessage12.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMessage12.setText("Docter Feedback:");

        txtOrphanMessageFromDr.setEnabled(false);

        lblMessage11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMessage11.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMessage11.setText("Pharmacy Feedback:");

        parFeedbackField.setEnabled(false);

        btnBack.setBackground(new java.awt.Color(252, 74, 26));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        SexField.setEditable(false);
        SexField.setRequestFocusEnabled(false);

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(lblTitle))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addComponent(lblMessage5))
                                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                    .addGap(89, 89, 89)
                                    .addComponent(lblMessage7))
                                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(lblMessage8))
                                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(lblMessage9))
                                .addComponent(lblMessage12))
                            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                .addComponent(lblMessage11)
                                .addGap(12, 12, 12)))
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parFeedbackField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtOrphanAge, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(txtOrphanfName)
                                    .addComponent(SexField)
                                    .addComponent(txtOrphanRace)
                                    .addComponent(txtOrphanMessageFromDr))
                                .addGap(47, 47, 47)
                                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(99, 99, 99))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle)
                .addGap(65, 65, 65)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMessage5)
                            .addComponent(txtOrphanfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblMessage7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtOrphanAge, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addComponent(lblMessage8)
                        .addGap(27, 27, 27)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMessage9)
                            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtOrphanRace, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMessage12)
                            .addComponent(txtOrphanMessageFromDr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parFeedbackField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMessage11))
                .addGap(76, 76, 76)
                .addComponent(btnBack))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrphanDetailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrphanDetailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrphanDetailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrphanDetailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOrphanDetailJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SexField;
    private javax.swing.JButton btnBack;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel lblMessage11;
    private javax.swing.JLabel lblMessage12;
    private javax.swing.JLabel lblMessage5;
    private javax.swing.JLabel lblMessage7;
    private javax.swing.JLabel lblMessage8;
    private javax.swing.JLabel lblMessage9;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField parFeedbackField;
    private javax.swing.JTextField txtOrphanAge;
    private javax.swing.JTextField txtOrphanMessageFromDr;
    private javax.swing.JTextField txtOrphanRace;
    private javax.swing.JTextField txtOrphanfName;
    // End of variables declaration//GEN-END:variables

    private void populateAllDetails() {

        txtOrphanfName.setText(this.o.getName());
        txtOrphanAge.setText(String.valueOf(this.o.getAge()));
        SexField.setText(this.o.getSex());
        txtOrphanRace.setText(this.o.getRace());
        txtOrphanMessageFromDr.setText(this.o.getDoctorMessage());
        parFeedbackField.setText(this.o.getPharmacyMessage());

        if (this.o.getPhoto() != null) {
            String path = Paths.get(this.o.getPhoto()).toAbsolutePath().toString();
            ImageIcon icon = seticon(path, null);
            lblPhoto.setIcon(icon);
        }
    }

    public ImageIcon seticon(String mess, byte[] image) {
        //set image icon
        ImageIcon i = null;

        if (mess != null) {
            i = new ImageIcon(mess);
        } else {
            i = new ImageIcon(image);
        }
        //set image icon
        Image imgone = i.getImage();
        Image imgtwo = imgone.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(imgtwo);
        return img;
    }
}
